### PR TITLE
Update appveyor.yml

### PR DESCRIPTION
**Pull request by toddlang**

### CODE REVIEW

**Comment by j3parker** [comment]
wtf @ the CI output?

**Comment by omsmith** [comment]
Tried re-running it, doesn't seem to have helped. If I had to guess, we're referencing some sort of package that isn't available on nuget.org, but that doesn't seem to be that case?

**Comment by j3parker** [comment]
It's weird, the build is passing without this change. What would be different on VS2017?

**Comment by toddlang** [comment]
Log looks like some kind of inability to get the required permissions to pull packages, no?

**Pull request closed without merging**
