### PR TITLE
US81987: exposing some AccessTokenExtensions methods for use in platf…

### PR DESCRIPTION
**Pull request by astadelbauer**
…ormTools/impersonation

### CODE REVIEW

**Comment by j3parker** [comment]
I'll bump the version and open a PR to use the new version in the LMS after CI passes & this is merged.

**Comment by omsmith** [comment]
Would we not just use `ID2LPrincipal`?

**Comment by astadelbauer** [comment]
ID2LPrincipal would be great, but we didn't think it would work since we're passing the token in the form post body and not actually doing authentication with it -- @j3parker understands more than I do :)

**Comment by omsmith** [comment]
Oh yeah, that part.

**Pull request merged**
